# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@aboutus
Feature: AboutUs

Background:
  Given user opens homepage

@low
@positive
Scenario: Verify 'About us' video plays successfully
  When user performs the action
  Then expected result should be displayed

