# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@about-us-(modal)
Feature: About Us (Modal)

Background:
  Given user opens homepage

@low
@positive
Scenario: Verify About Us video can be played
  When user performs the action
  Then expected result should be displayed

