# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@about-us-(modal)
Feature: About us (Modal)

Background:
  Given user opens homepage

@low
@smoke
Scenario: Verify About us video loads and plays
  When user performs the action
  Then expected result should be displayed

