# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@any-(after-login)
Feature: Any (after login)

Background:
  Given user opens homepage

@high
@smoke
Scenario: Verify successful user logout
  When user performs the action
  Then expected result should be displayed

