# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@cart
Feature: Cart

Background:
  Given user opens homepage

@high
@regression
Scenario: Verify items are correctly displayed in the cart page
  When user adds a product to the cart
  Then cart should contain the product

@high
@regression
Scenario: Verify removing a product from the cart
  When user adds a product to the cart
  Then cart should contain the product

