# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@cart
Feature: Cart

Background:
  Given user opens homepage

@high
@regression
Scenario: Verify navigation to the Cart page
  When user adds a product to the cart
  Then cart should contain the product

