# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@contact
Feature: Contact

Background:
  Given user opens homepage

@low
@positive
Scenario: Verify sending a contact message with valid data
  When user performs the action
  Then expected result should be displayed

