# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@contact-(modal)
Feature: Contact (Modal)

Background:
  Given user opens homepage

@low
@positive
Scenario: Verify sending a contact message successfully
  When user performs the action
  Then expected result should be displayed

@low
@negative
Scenario: Verify contact form validation for empty fields
  When user performs the action
  Then expected result should be displayed

