# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@home-(about-us-video)
Feature: Home (About Us Video)

Background:
  Given user opens homepage

@low
@positive
Scenario: Verify 'About us' video modal opens and video plays
  When user performs the action
  Then expected result should be displayed

