# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@home
Feature: Home

Background:
  Given user opens homepage

@medium
@regression
Scenario: Verify product filtering by category (Phones)
  When user opens a product
  Then product details should be displayed

@medium
@regression
Scenario: Verify product pagination (Next/Previous buttons)
  When user opens a product
  Then product details should be displayed

