# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@home-(contact)
Feature: Home (Contact)

Background:
  Given user opens homepage

@low
@positive
Scenario: Verify sending a contact message successfully
  When user performs the action
  Then expected result should be displayed

@low
@negative
Scenario: Verify contact form displays validation errors for empty fields
  When user performs the action
  Then expected result should be displayed

