# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@login-(modal)
Feature: Login (Modal)

Background:
  Given user opens homepage

@high
@smoke
Scenario: Verify successful user login
  When user logs in with valid credentials
  Then user should be logged in successfully

@high
@negative
Scenario: Verify login with invalid credentials
  When user logs in with invalid credentials
  Then an error message should be displayed

