# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@place-order-(modal)
Feature: Place Order (Modal)

Background:
  Given user opens homepage

@high
@regression
Scenario: Verify successful purchase order submission
  When user performs the action
  Then expected result should be displayed

@high
@negative
Scenario: Verify purchase order with incomplete information
  When user performs the action
  Then expected result should be displayed

