# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@product
Feature: Product

Background:
  Given user opens homepage

@medium
@positive
Scenario: Verify product details page loads correctly
  When user opens a product
  Then product details should be displayed

@high
@regression
Scenario: Verify adding a product to cart from product page
  When user adds a product to the cart
  Then cart should contain the product

