# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@productdetails
Feature: ProductDetails

Background:
  Given user opens homepage

@medium
@positive
Scenario: Verify product details page loads with correct information
  When user opens a product
  Then product details should be displayed

