# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@product
Feature: Product

Background:
  Given user opens homepage

@medium
@positive
Scenario: Verify navigating to a product details page
  When user opens a product
  Then product details should be displayed

@high
@regression
Scenario: Verify adding a product from product details page to cart
  When user adds a product to the cart
  Then cart should contain the product

