# ==========================================
# Generated by AI QA Automation Framework
# Do not edit manually.
# ==========================================

@sign-up-(modal)
Feature: Sign Up (Modal)

Background:
  Given user opens homepage

@high
@smoke
Scenario: Verify successful user registration
  When user registers with valid information
  Then account should be created successfully

@high
@negative
Scenario: Verify registration with existing username
  When user registers with valid information
  Then account should be created successfully

