import { Scenario } from "../models/Scenario";
import { GherkinTemplateEngine } from "../templates/GherkinTemplateEngine";

export class FeatureGenerator {

    generate(scenarios: Scenario[]): Map<string, string> {

        const engine = new GherkinTemplateEngine();

        const grouped = new Map<string, Scenario[]>();

        // =========================
        // Group scenarios by feature
        // =========================

        for (const scenario of scenarios) {

            if (!grouped.has(scenario.feature)) {
                grouped.set(scenario.feature, []);
            }

            grouped.get(scenario.feature)!.push(scenario);

        }

        const features = new Map<string, string>();

        // =========================
        // Generate .feature files
        // =========================

        for (const [featureName, featureScenarios] of grouped) {

            const normalizedFeatureName = this.normalizeFeatureName(featureName);

            let content = "";

            // =========================
            // Header
            // =========================

            content += "# ==========================================\n";
            content += "# Generated by AI QA Automation Framework\n";
            content += "# Do not edit manually.\n";
            content += "# ==========================================\n\n";

            // =========================
            // Feature Tag
            // =========================

            content += `@${this.getFeatureTag(normalizedFeatureName)}\n`;

            // =========================
            // Feature
            // =========================

            content += `Feature: ${normalizedFeatureName}\n\n`;

            // =========================
            // Background
            // =========================

            content += "Background:\n";
            content += "  Given user opens homepage\n\n";

            // =========================
            // Scenarios
            // =========================

            for (const scenario of featureScenarios) {

                // Scenario Tags
                for (const tag of scenario.tags) {
                    content += `${tag}\n`;
                }

                // Scenario Title
                content += `Scenario: ${scenario.title}\n`;

                // Scenario Steps
                const steps = engine.build(scenario);

                for (const step of steps) {
                    content += `  ${step}\n`;
                }

                content += "\n";

            }

            features.set(normalizedFeatureName, content);

        }

        return features;

    }

    // =========================
    // Helpers
    // =========================

    private normalizeFeatureName(featureName: string): string {

        switch (featureName.trim().toLowerCase()) {

            case "log in":
                return "Login";

            case "sign up":
                return "Signup";

            case "about us":
                return "AboutUs";

            case "product details":
                return "ProductDetails";

            default:
                return featureName.trim();

        }

    }

    private getFeatureTag(featureName: string): string {

        return featureName
            .toLowerCase()
            .replace(/\s+/g, "-");

    }

}